name: make_an_example_for_quan
description: bo sung sau.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  image_picker_web: ^2.0.3+1
  mime_type: ^1.0.0

flutter:
  uses-material-design: true
